### ISSUE TITLE
Where can I configure redis?

### ISSUE THREAD

**Issue by asaarashi** [ekosuhariyadi/yii2-resque#2]
It takes 127.0.0.1:6379 as Redis configuration for default, how can I change it?
I've tried modifying both vendor/codeimpact/yii2-resque/config.yml and vendor/mjphaynes/php-resque/config.yml, but it did not take effect.

**Comment by asaarashi** [comment]
Got it. It requires specifying config file  with "-c" parameter manually in console command yii2resque.

**Comment by asaarashi** [comment]
hope you can mention that in README ;)

**Comment by ekosuhariyadi** [comment]
May be you forgot about step number 2
- Copy vendor/codeimpact/yii2-resque/config.yml to folder where your project's composer.json exists (project's root).
- Then you can modify your need

because the command by default looking for config,yml at project root, or yes you can specify config file location just like your answer

**Comment by asaarashi** [comment]
Yes, thank you! But my preferred way is to specify a config file path so that I can put it in config/ path to separate config file for dev/prod environment.
